FROM node:23.11.0-slim

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /usr/src/app


COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm install

COPY . .

RUN pnpm build

EXPOSE 3000
EXPOSE 4200

CMD [ "node", "dist/main.js" ]